name: Start kuzzle server
description: Start kuzzle server

inputs:
  KUZZLE_IMAGE:
    description: Kuzzle image target
    required: true

runs:
  using: "composite"
  steps:
    - run: npm install
      shell: bash
    - run: npm run build
      shell: bash
    - run: npm prune --production
      shell: bash
    - run: |
        export KUZZLE_IMAGE=${{ inputs.KUZZLE_IMAGE }}
        docker-compose -f ./.ci/services.yml up -d
      shell: bash
    - run: |
        trap 'docker-compose -f ./.ci/services.yml logs' err

        export MAX_TRIES=120
        ./bin/wait-kuzzle

        trap - err
      shell: bash
    - run: docker-compose -f ./.ci/services.yml down
      shell: bash
