version: '3'

services:
  kuzzle:
    build:
      dockerfile: ../docker/images/${KUZZLE_IMAGE}/Dockerfile
      context: ..

    command: ["kuzzle", "start"]
    volumes:
      - "..:/var/app"
    cap_add:
      - SYS_PTRACE
    ulimits:
      nofile: 65536
    sysctls:
      - net.core.somaxconn=8192
    ports:
      - "7512:7512"
    depends_on:
      - redis
      - elasticsearch

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  elasticsearch:
    image: kuzzleio/elasticsearch:7
    ports:
      - "9200:9200"
    ulimits:
      nofile: 65536
